config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flats
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :price_per_night, numericality: { greater_than_or_equal_to: 0 }
  validates :number_of_guests, numericality: { greater_than_or_equal_to: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  # Action to display a list of all flats
  def index
    @flats = Flat.all
  end
  # Action to display a single flat
  def show
    @flat = Flat.find(params[:id])
  end

  # Action to show the form for creating a new flat
  def new
    @flat = Flat.new
  end

  # Action to create a new flat in the database
  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created.'
    else
      render :new
    end
  end

  # Action to show the form for editing an existing flat
  def edit
    @flat = Flat.find(params[:id])
  end

  # Action to update the details of an existing flat
  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat was successfully updated.'
    else
      render :edit
    end
  end

  # Action to destroy a flat
  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, notice: 'Flat was successfully deleted.'
  end

  private

  # Strong parameters to permit the flat's attributes
  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit Flat</h1>

<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>

  <%= f.submit 'Update Flat' %>
<% end %>

app/views/flats/index.html.erb
<h1>All Flats</h1>

<ul>
  <% @flats.each do |flat| %>
    <li>
      <%= link_to flat.name, flat_path(flat) %> - <%= flat.price_per_night %> per night
      <%= link_to 'Delete', flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>

  <%= f.submit 'Create Flat' %>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

<p><strong>Address:</strong> <%= @flat.address %></p>
<p><strong>Description:</strong> <%= @flat.description %></p>
<p><strong>Price per night:</strong> <%= @flat.price_per_night %></p>
<p><strong>Number of guests:</strong> <%= @flat.number_of_guests %></p>

<%= link_to 'Edit', edit_flat_path(@flat) %>
<%= link_to 'Back', flats_path %>
<%= link_to 'Delete', %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>